/**
 * action-tyes
 */
export const GET_COMMENTS="GET_COMMENTS"
export const GET_MOVIES='GET_MOVIES'
export const RESET_MOVIES='RESET_MOVIES'
export const CHANGE_RE='CHANGE_RE'
export const GET_LOCATION='GET_LOCATION'
export const SEARCH_LOCATIONS='SEARCH_LOCATIONS'
export const GET_USER='GET_USER'
export const GET_MESSAGES="GET_MESSAGES"
export const UPDATE_USER="UPDATE_USER"
export const UPDATE_MESSAGES="UPDATE_MESSAGES"
export const DELETE_LOGIN="DELETE_LOGIN"
export const MSGDELETE_LOGIN='MSGDELETE_LOGIN'